
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 * Questo programma é lo start della applicazione 
 * 
 * @author alesassandro Aloise
 * @version 20.12.2019
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form Startframe
     */
    public StartFrame() {
        this.setTitle("Fiocco di neve");
        initComponents();
        this.setSize(1024, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        default1 = new javax.swing.JButton();
        default2 = new javax.swing.JButton();
        default3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBackground(new java.awt.Color(96, 96, 96));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/fiocco.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(136, 205, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Start");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(136, 205, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Carica");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(136, 205, 255));
        jLabel1.setText("Fiocco di neve ");

        default1.setBackground(new java.awt.Color(96, 96, 96));
        default1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        default1.setForeground(new java.awt.Color(96, 96, 96));
        default1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/default/default1.png"))); // NOI18N
        default1.setBorder(null);
        default1.setBorderPainted(false);
        default1.setContentAreaFilled(false);
        default1.setMaximumSize(new java.awt.Dimension(150, 150));
        default1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default1ActionPerformed(evt);
            }
        });

        default2.setBackground(new java.awt.Color(96, 96, 96));
        default2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        default2.setForeground(new java.awt.Color(96, 96, 96));
        default2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/default/default3.png"))); // NOI18N
        default2.setBorder(null);
        default2.setBorderPainted(false);
        default2.setContentAreaFilled(false);
        default2.setMaximumSize(new java.awt.Dimension(150, 150));
        default2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default2ActionPerformed(evt);
            }
        });

        default3.setBackground(new java.awt.Color(96, 96, 96));
        default3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        default3.setForeground(new java.awt.Color(96, 96, 96));
        default3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/default/default2.png"))); // NOI18N
        default3.setBorder(null);
        default3.setBorderPainted(false);
        default3.setContentAreaFilled(false);
        default3.setMaximumSize(new java.awt.Dimension(150, 150));
        default3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(136, 205, 255));
        jLabel3.setText("Modelli di Default");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(default2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(default3, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(default1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(default1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(default3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(default2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(602, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new FioccoDiNeve().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser open = new JFileChooser();
        File directory = new File("Fiocchi di neve");
        if (!directory.exists()) {
            directory.mkdirs();
        }
        open.setCurrentDirectory(directory);
        FileNameExtensionFilter fnf = new FileNameExtensionFilter("Snowflake file (*.snowflake)", "snowflake");
        open.setFileFilter(fnf);
        open.showDialog(null, "Open");
        try {
            String handle = open.getSelectedFile().toString();
            FioccoDiNeve fiocco = new FioccoDiNeve(true, handle);
            fiocco.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException npe) {
            System.out.println("Closed");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void default1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_default1ActionPerformed
        JFileChooser open = new JFileChooser();
        File directory = new File("foto");
        open.setCurrentDirectory(directory);
        try {
            String handle = directory +"\\default\\default1.snowflake";
            FioccoDiNeve fiocco = new FioccoDiNeve(true, handle);
            fiocco.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException npe) {
            System.out.println("Closed");
        }
    }//GEN-LAST:event_default1ActionPerformed

    private void default2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_default2ActionPerformed
       JFileChooser open = new JFileChooser();
        File directory = new File("foto");
        open.setCurrentDirectory(directory);
        try {
            String handle = directory +"\\default\\default2.snowflake";
            FioccoDiNeve fiocco = new FioccoDiNeve(true, handle);
            fiocco.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException npe) {
            System.out.println("Closed");
        }
    }//GEN-LAST:event_default2ActionPerformed

    private void default3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_default3ActionPerformed
        JFileChooser open = new JFileChooser();
        File directory = new File("foto");
        open.setCurrentDirectory(directory);
        try {
            String handle = directory +"\\default\\default3.snowflake";
            FioccoDiNeve fiocco = new FioccoDiNeve(true, handle);
            fiocco.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException npe) {
            System.out.println("Closed");
        }
    }//GEN-LAST:event_default3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton default1;
    private javax.swing.JButton default2;
    private javax.swing.JButton default3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
